[build]
command = "yarn build"
publish = "dist"
[build.processing]
skip_processing = true
[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"

[[plugins]]
package = "netlify-plugin-minify-html"
[plugins.inputs]
contexts = [
    'production',
    'branch-deploy',
    'deploy-preview'
]

[[plugins]]
package = "netlify-plugin-cypress"

[[plugins]]
package = "@netlify/plugin-lighthouse"
[plugins.inputs.thresholds]
performance = 0.8
accessibility = 0.9
best-practices = 0.9
seo = 0.9
[plugins.inputs]
output_path = "./lighthouse.html"
