[build]
command = "yarn build"
publish = "dist"

[build.environment]
# Cache Cypress binary in local "node_modules" folder so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# Set TERM variable for Cypress terminal output
TERM = "xterm"

[[plugins]]
package = "netlify-plugin-cypress"
[plugins.inputs.preBuild]
enable = true
start = 'yarn start'
wait-on = 'http://localhost:8080'
wait-on-timeout = '30' # seconds
